//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargotakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int ID { get; set; }
        public string Adsoyad { get; set; }
        public string telno { get; set; }
        public string email { get; set; }
        public string kuladı { get; set; }
        public string sifre { get; set; }
    }
}
