//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargotakipSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KTSEntities1 : DbContext
    {
        public KTSEntities1()
            : base("name=KTSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<ilceler> ilcelers { get; set; }
        public virtual DbSet<iletisim> iletisims { get; set; }
        public virtual DbSet<iller> illers { get; set; }
        public virtual DbSet<mesaj> mesajs { get; set; }
        public virtual DbSet<takip> takips { get; set; }
        public virtual DbSet<tbl_il> tbl_il { get; set; }
        public virtual DbSet<tbl_ilce> tbl_ilce { get; set; }
        public virtual DbSet<tbl_semt> tbl_semt { get; set; }
        public virtual DbSet<üye> üye { get; set; }
        public virtual DbSet<tbl_pk> tbl_pk { get; set; }
    }
}
