//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargotakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class takip
    {
        public int Kargono { get; set; }
        public string Gadsoyad { get; set; }
        public string Gadres { get; set; }
        public string Gtelno { get; set; }
        public string Aadsoyad { get; set; }
        public string Aadres { get; set; }
        public string Atelno { get; set; }
        public string Durum { get; set; }
    }
}
